name: Autodeploy branch

on:
  push:
    branches:
     - test-deploy
     - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install node dependencies
      run: npm install
    - name: Run build
      run: npm run build
    - name: Archive build artifacts
      working-directory: build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          .
          !latest.json
