name: Autodeploy branch

on:
  push:
    branches:
     - test-deploy
     - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install node dependencies
      run: npm install
    - name: Run build
      run: npm run build
    - name: Remove latest.json
      run: rm build/latest.json
    - name: Deploy to Scripts
      uses: wsmoses/action-deploy-scripts@main
      with:
        locker: 'hydrant'
        privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        local: build
        remote: hydrant/test_deploy
